### ISSUE TITLE
Aardvark.Base.ImageLoadException:“could not load image”

### ISSUE THREAD

**Issue by fengfxg** [aardvark-community/Aardvark.OpenImageDenoise#1]
hi man,i use your Aardvark.OpenImageDenoise0.3.0 for nuget,Encounter this exception..

```cs
using Aardvark.Base;
using Aardvark.OpenImageDenoise;
using System;
using System.IO;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello Denoise!");

            using (var dnDevice = new Device())
            {
                Console.WriteLine("Using {0} Threads", dnDevice.NumThreads);

                Denoise(dnDevice, @"D:\code\cycles\cycles\build\bin\Release\bbb.exr");
               
            }
            Console.ReadLine();
        }

        static void Denoise(Device device, string file)
        {
            if (!File.Exists(file))
            {
                Console.WriteLine("File Not Exists!");
                return;
            }

            //here  Aardvark.Base.ImageLoadException:“could not load image”
            var img4Chan = (PixImage<float>)PixImage.Create(file,PixLoadOptions.Default);

            var img = img4Chan.ToPixImage<float>(Col.Format.RGB);
    
            var resultImg = device.Denoise(img, 10);   

            var outFile = Path.GetFileNameWithoutExtension(file) + "_dn.exr";
            resultImg.SaveAsImage(outFile);

            Console.WriteLine("Denoise -> OK");
        }
    }
}
```

**Comment by luithefirst** [comment]
In the latest Aardvark release (5.2) we dropped DevIL as default image loader and switched to ImageSharp that unfortunately does not properly support exr. You can still use DevIL, but need to manually install the [Aardvark.PixImage.DevIL](https://www.nuget.org/packages/Aardvark.PixImage.DevIL/) package (does not run on all platforms).

You might also need to also run Aardvark.Base.Aardvark.Init() on startup in order to register the additional loader properly.

I can later try to reproduce the issue since I guess also the test project in this repo is no longer working.

**Comment by krauthaufen** [comment]
DevIL should actually be working on all platforms.

**Comment by krauthaufen** [comment]
DevIL should actually be working on all platforms.

**Comment by fengfxg** [comment]
thank you very much for your reply. the DenoiseTest example code is ok,but only run in dotnet core 3.1.

 thank you!
